language: ruby
sudo: required
rvm:
  - 2.0.0-p648
  - 2.1.8
  - 2.2.3
  - 2.3.1
cache: bundler
services:
  - docker
before_install:
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
  - echo "deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.0.list
  - sudo apt-get update
  - sudo apt-get remove -y -q --purge mongodb-org*
  - sudo rm -rf /var/lib/mongodb
  - sudo apt-get install -y -q -f mongodb-org-server=3.0.12
env:
  global:
    - secure: "mM0iv3ooqyqYsbBBNw73/88EURi5PO529E2Sm2ovy5xzL0SadOyCz4uLYmTMiIoP+pXDvmH1/XjoPxVLR2MH4shXe0VtrKFYiTEjan3X05VUyVMnfnm0Z+uMgHsBFZxl941o27N0jFY+0dcAstofprP/PF5SxKvKwcb0rCfdUYs="
    - secure: "YKHqxWKFfrhJoQ5ptfgnByGNdcRLcQVpI22EGjU5WWzQrUw3Frq8+zsRmSNjzF6qEi5oXfxzxUaOItzY8W8bkWUVHCaVGalfyK+C4ad55n8ZpP2cZkOJtenocPhhUTRFwOuAZsUYCI+hXroMyoBUsnu4AJqpkYVimlNblOdcWoA="
  matrix:
    - TEST_DIR=agent
    - TEST_DIR=cli
    - TEST_DIR=server
matrix:
  exclude:
    - rvm: 2.0.0-p648
      env: TEST_DIR=server
    - rvm: 2.1.8
      env: TEST_DIR=server
    - rvm: 2.2.3
      env: TEST_DIR=server
    - rvm: 2.0.0-p648
      env: TEST_DIR=agent
    - rvm: 2.1.8
      env: TEST_DIR=agent
    - rvm: 2.2.3
      env: TEST_DIR=agent
script: ./travis.sh
deploy:
  - provider: script
    script: "rvm $TRAVIS_RUBY_VERSION do $TRAVIS_BUILD_DIR/publish.sh"
    on:
      tags: true
      condition: $TEST_DIR = server
      rvm: 2.3.1
      repo: kontena/kontena
