language: ruby
sudo: required
rvm:
  - 2.0.0-p648
  - 2.1.8
  - 2.2.3
  - 2.3.1
cache: bundler
cache:
  directories:
  - $TEST_DIR/vendor/bundle
services:
  - docker
before_install:
  - ./build/travis/before_install.sh
env:
  global:
    - secure: "mM0iv3ooqyqYsbBBNw73/88EURi5PO529E2Sm2ovy5xzL0SadOyCz4uLYmTMiIoP+pXDvmH1/XjoPxVLR2MH4shXe0VtrKFYiTEjan3X05VUyVMnfnm0Z+uMgHsBFZxl941o27N0jFY+0dcAstofprP/PF5SxKvKwcb0rCfdUYs="
    - secure: "VscHll68/TaRqUOPvpUEhxcb4t1eXXpS0GPl+gsC9wQUAkC4Vbgjhl4d3UDCi1YoqYEz5ykvzHzYvFU87Eq9zvkdPn2AHWLkJhOEnEzKh/CpyC+Yk+iWKLt+1E1CyJZLUylroCxERPxlLdZKdv0+3Jh18NviDh86mKzGriUoXNM="
  matrix:
    - TEST_DIR=agent
    - TEST_DIR=cli
    - TEST_DIR=server
matrix:
  exclude:
    - rvm: 2.0.0-p648
      env: TEST_DIR=server
    - rvm: 2.1.8
      env: TEST_DIR=server
    - rvm: 2.2.3
      env: TEST_DIR=server
    - rvm: 2.0.0-p648
      env: TEST_DIR=agent
    - rvm: 2.1.8
      env: TEST_DIR=agent
    - rvm: 2.2.3
      env: TEST_DIR=agent
script: ./build/travis/test.sh
deploy:
  - provider: script
    script: "rvm $TRAVIS_RUBY_VERSION do $TRAVIS_BUILD_DIR/build/travis/deploy.sh"
    on:
      tags: true
      condition: $TEST_DIR = server
      rvm: 2.3.1
      repo: kontena/kontena
