api:
  build: .
  ports:
    - 4040:9292
  environment:
    - RACK_ENV=production
    - REDIS_URL=redis://redis:6379/1
    - MONGODB_URI=mongodb://mongodb:27017/kontena_development
  links:
   - redis
   - mongodb
redis:
  image: redis:2.8
  command: redis-server --appendonly yes
mongodb:
  image: mongo:2.8
  command: mongod --smallfiles
