agent:
  container_name: kontena-agent
  build: .
  dockerfile: Dockerfile.alpine
  env_file: .env
  environment:
    - KONTENA_PEER_INTERFACE=eth1
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
